### ISSUE TITLE
Feature Request - Report subscribers per Service and per Sub-service

### ISSUE THREAD

**Issue by italovalcy** [amlight/Services-Status#7]
It would be interesting and very useful to have the report of Subscribers per Service and per Sub-Service.

Currently, the way to see the subscribers of a particular Service is click on each Subscriber, one by one, and go over all of them checking if the checked the Service. As the number of users grown, this makes the task of checking the subscribers more complicated and time consuming. As a suggestion, in the Sub-Service and Service page, it would have the relationship with subscripts and then the admin can see and change it over there.

The feature is under the Admin page.

**Comment by ArturoQuintana** [comment]
This request has been implemented. 
Besides, we added the possibility to filter by Region and by ClientDomain, supporting the option to get a "report" about those users subscribed to services and/or sub-services who belong to certain Regions or Domains.
